### ISSUE TITLE
dof6_estimator CMakeLists.txt is missing 

### ISSUE THREAD

**Issue by gyubeomim** [huangxueyan/PEME#1]
Hello Huang, 

Thank you for sharing such a nice work. When I tried to build your code, there is an error occurred that 'CMakeLists.txt' of dof6_estimator is missing. Could you upload it please?

Thanks in advance.

**Comment by huangxueyan** [comment]
The 6Dof code architecture is very similar to the rotational code, so you can construct a CMakeList based on it, eg, copy the Cmakelist in rotational code and change the "add_executable" commands in it.
